# Assignment-3
---

**1.1: Write a function to compute 5/0 and use try/except to catch the exceptions**

In [3]:
def divide(num1,num2):
    try:
        print(f"The division result of {num1}/{num2} is {num1/num2}")
    
    except ZeroDivisionError:
        print("A number cannot be divided by a zero")
    except Exception as e:
        print(f"Exception occured: {str(e)}")

#trial 1
divide(5,2)
print()

# trial2
divide(5,0)
print()

# trial3
divide(10,5)
print()

# trial4
divide('hello','world')

The division result of 5/2 is 2.5

A number cannot be divided by a zero

The division result of 10/5 is 2.0

Exception occured: unsupported operand type(s) for /: 'str' and 'str'


**1.2: Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].**

***Hint: Subject,Verb and Object should be declared in the program as shown below.***

* subjects=["Americans ","Indians"]
* verbs=["play","watch"]
* objects=["Baseball","Cricket"]

Output should come as below:

        Americans play Baseball.
        Americans play Cricket.
        Americans watch Baseball.
        Americans watch Cricket.
        Indians play Baseball.
        Indians play Cricket.
        Indians watch Baseball.
        Indians watch Cricket.

In [8]:
subjects = ['Americans', 'Indians']
verbs = ['play', 'watch']
objects = ['Baseball','Cricket']

print(*[f"{sub} {ver} {obj}" for sub in subjects for ver in verbs for obj in objects], sep='\n')

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


**2.1: Write a function so that the columns of the output matrix are powers of the input vector.**

*The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.*


***HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.***


In [27]:
import numpy as np

def vander(input_array, N=None, increasing=False):
    if N == None:
        N = len(input_array)
    van_mat = np.array([input_array**(N-1-i) for i in range(N)])
    if increasing:
        return van_mat.T[:,::-1]
    return van_mat.T

# test 1:
array1 = np.random.randint(1,9,5)
print("input_array: ", array1)
print()
print("vandermonde matrix: ", vander(array1), sep="\n")
print()

# test 2:
array1 = np.random.randint(1,9,8)
print("input_array: ", array1)
print()
N=3
print("vandermonde matrix: ", vander(array1, N), sep="\n")
print()

# test 3:
array1 = np.array([1,2,3,4,5])
print("input_array: ", array1)
print()
print("vandermonde matrix: ", vander(array1, increasing=True), sep="\n")

input_array:  [4 1 6 8 3]

vandermonde matrix: 
[[ 256   64   16    4    1]
 [   1    1    1    1    1]
 [1296  216   36    6    1]
 [4096  512   64    8    1]
 [  81   27    9    3    1]]

input_array:  [6 5 4 5 3 1 1 5]

vandermonde matrix: 
[[36  6  1]
 [25  5  1]
 [16  4  1]
 [25  5  1]
 [ 9  3  1]
 [ 1  1  1]
 [ 1  1  1]
 [25  5  1]]

input_array:  [1 2 3 4 5]

vandermonde matrix: 
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
